name: precio_medio_paraguay
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  uno: ^1.1.4
  dartz:
  google_maps_flutter: ^2.2.5
  rx_notifier: ^2.2.0+2
  dio:
  url_launcher: ^6.1.10
  mocktail: ^0.3.0
  intl: ^0.18.1
  collection: ^1.17.0
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  mask_text_input_formatter: ^2.4.0
  fake_cloud_firestore: ^2.4.1+1
  location: ^4.4.0
  shared_preferences: ^2.1.2
  http:

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/paraguay_mapa.svg
    - assets/mapa_paraguay.jpg
    - assets/mapa_paraguay.png
    - assets/dev_py_logo.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
