final departamentosComCidades = [
  {
    "name": "Central",
    "capital": "Areguá",
    "cidades": [
      "Asunción",
      "Areguá",
      "Capiatá",
      "Fernando de la Mora",
      "Guarambaré",
      "Itá",
      "Itauguá",
      "J. Augusto Saldivar",
      "Lambaré",
      "Limpio",
      "Luque",
      "Mariano Roque Alonso",
      "Nemby",
      "Nueva Italia",
      "San Antonio",
      "San Lorenzo",
      "Villa Elisa",
      "Villeta",
      "Ypacaraí",
      "Ypané"
    ]
  },
  {
    "name": "Concepción",
    "capital": "Concepción",
    "cidades": [
      "Arroyito",
      "Azotey",
      "Belén",
      "Concepción",
      "Horqueta",
      "Loreto",
      "San Carlos del Apa",
      "San Lázaro",
      "Yby Yaú",
      "Sargento José Félix López",
      "San Alfredo",
      "Paso Barreto"
    ]
  },
  {
    "name": "San Pedro",
    "capital": "San Pedro de Ycuamandiyú",
    "cidades": [
      "Antequera",
      "Capiibary",
      "Choré",
      "General Elizardo Aquino",
      "General Isidoro Resquín",
      "Guayaibí",
      "Itacurubí del Rosario",
      "Liberación",
      "Lima",
      "Rio Verde",
      "Nueva Germania",
      "San Estanislao",
      "San Pablo",
      "Villa de San Pedro",
      "San Vicente Pancholo",
      "Santa Rosa del Aguaray",
      "Tacuatí",
      "Unión",
      "25 de Diciembre",
      "Villa del Rosario",
      "Yataity del Norte",
      "Yrybucuá"
    ]
  },
  {
    "name": "Coordillera",
    "capital": "Caacupé",
    "cidades": [
      "Altos",
      "Arroyos y Esteros",
      "Atyrá",
      "Caacupé",
      "Caraguatay",
      "Emboscada",
      "Eusebio Ayala",
      "Isla Pucú",
      "Itacurubí",
      "Juan de Mena",
      "Loma Grande",
      "Mbocayaty del Yhaguy",
      "Nueva Colombia",
      "Piribebuy",
      "Primero de Marzo",
      "San Bernardino",
      "San José Obrero",
      "Santa Elena",
      "Tobatí",
      "Valenzuela"
    ]
  },
  {
    "name": "Guairá",
    "capital": "Villarica",
    "cidades": [
      "Borja",
      "Colonia Independencia",
      "Coronel Martínez",
      "Dr. Bottrell",
      "Fassardi",
      "Félix Pérez Cardozo",
      "Garay",
      "Itapé",
      "Iturbe",
      "Mbocayaty",
      "Natalicio Talavera",
      "Numí",
      "Paso Yobái",
      "San Salvador",
      "Tebicuary",
      "Troche",
      "Villarrica",
      "Yataity"
    ]
  },
  {
    "name": "Caaguazú",
    "capital": "Coronel Oviedo",
    "cidades": [
      "Caaguazú",
      "Carayaó",
      "Cnel. Oviedo",
      "Doctor Cecilio Báez",
      "J.E. Estigarribia",
      "Campo 9",
      "Doctor Juan Manuel Frutos",
      "José Domingo Ocampos",
      "La Pastora",
      "Mcal. Francisco S. López",
      "Nueva Londres",
      "Nueva Toledo",
      "Raúl Arsenio Oviedo",
      "Repatriación",
      "R. I. Tres Corrales",
      "San Joaquín",
      "San José de los Arroyos",
      "Mbutuy",
      "Simón Bolívar",
      "Tembiaporá",
      "Tres de Febrero",
      "Vaquería",
      "Yhú"
    ]
  },
  {
    "name": "Caazapá",
    "capital": "Caazapá",
    "cidades": [
      "3 de Mayo",
      "Abaí",
      "Buena Vista",
      "Caazapá",
      "Doctor Moisés S. Bertoni",
      "Fulgencio Yegros",
      "General Higinio Morínigo",
      "Maciel",
      "San Juan Nepomuceno",
      "Tavaí",
      "Yuty"
    ]
  },
  {
    "name": "Itapúa",
    "capital": "Encarnación",
    "cidades": [
      "Alto Verá",
      "Bella Vista",
      "Cambyretá",
      "Capitán Meza",
      "Capitán Miranda",
      "Carlos Antonio López",
      "Carmen del Paraná",
      "Coronel Bogado",
      "Edelira",
      "Encarnación",
      "Fram",
      "General Artigas",
      "General Delgado",
      "Hohenau",
      "Itapúa Poty",
      "Jesús",
      "Colonia La Paz",
      "José Leandro Oviedo",
      "Mayor Otaño",
      "Natalio",
      "Nueva Alborada",
      "Obligado",
      "Pirapó",
      "San Cosme y Damián",
      "San Juan del Paraná",
      "San Pedro del Paraná",
      "San Rafael del Paraná",
      "Maria Auxiliadora",
      "Trinidad",
      "Yatytay"
    ]
  },
  {
    "name": "Misiones",
    "capital": "San Juan Bautista",
    "cidades": [
      "Ayolas",
      "San Ignacio",
      "San Juan Bautista",
      "San Miguel",
      "San Patricio",
      "Santa María",
      "Santa Rosa",
      "Santiago",
      "Villa Florida",
      "Yabebyry"
    ]
  },
  {
    "name": "Paraguarí",
    "capital": "Paraguarí",
    "cidades": [
      "Acahay",
      "Caapucú",
      "Carapeguá",
      "Escobar",
      "Gral. Bernardino Caballero",
      "La Colmena",
      "María Antonia",
      "Mbuyapey",
      "Paraguarí",
      "Pirayú",
      "Quiindy",
      "Quyquyhó",
      "San Roque González de Santa Cruz",
      "Sapucai",
      "Tebicuarymí",
      "Yaguarón",
      "Ybycuí",
      "Ybytymí"
    ]
  },
  {
    "name": "Alto Paraná",
    "capital": "Ciudad del Este",
    "cidades": [
      "Ciudad del Este",
      "Doctor Juan León Mallorquín",
      "Doctor Raúl Peña",
      "Domingo Martínez de Irala",
      "Hernandarias",
      "Iruña",
      "Itakyry",
      "Juan E. O'Leary",
      "Los Cedrales",
      "Mbaracayú",
      "Minga Guazú",
      "Minga Porá",
      "Naranjal",
      "Nacunday",
      "Presidente Franco",
      "San Alberto",
      "San Cristóbal",
      "Santa Fe del Paraná",
      "Santa Rita",
      "Santa Rosa del Monday",
      "Tavapy",
      "Colonia Yguazú"
    ]
  },
  {
    "name": "Ñeembucú",
    "capital": "Pilar",
    "cidades": [
      "Alberdi",
      "Cerrito",
      "Desmochados",
      "General José Eduvigis Díaz",
      "Guazú Cuá",
      "Humaitá",
      "Isla Umbú",
      "Laureles",
      "Mayor José J. Martínez",
      "Paso de Patria",
      "Pilar",
      "San Juan Bautista del Ñeembucú",
      "Tacuaras",
      "Villa Franca",
      "Villalbín",
      "Villa Oliva"
    ]
  },
  {
    "name": "Amambay",
    "capital": "Pedro Juan Caballero",
    "cidades": [
      "Bella Vista Norte",
      "Capitán Bado",
      "Pedro Juan Caballero",
      "Zanja Pytá",
      "Karapaí"
    ]
  },
  {
    "name": "Canindeyú",
    "capital": "Salto del Guairá",
    "cidades": [
      "Colonia Anahí",
      "Corpus Christi",
      "Curuguaty",
      "Gral. Francisco Caballero Álvarez",
      "Itanará",
      "Katueté",
      "La Paloma",
      "Maracaná",
      "Nueva Esperanza",
      "Saltos del Guairá",
      "Villa Ygatimí",
      "Yasy Cañy",
      "Ybyrarovaná",
      "Ypejhú",
      "Yby Pytá"
    ]
  },
  {
    "name": "Presidente Hayes",
    "capital": "Villa Hayes",
    "cidades": [
      "Benjamín Aceval",
      "Dr. José Falcón",
      "General José María Bruguez",
      "Nanawa",
      "Colonia Paratodo",
      "Pozo Colorado",
      "Puerto Pinasco",
      "Tte. Irala Fernández",
      "Esteban Martínez",
      "Villa Hayes"
    ]
  },
  {
    "name": "Boquerón",
    "capital": "Filadelfia",
    "cidades": [
      "Filadelfia",
      "Loma Plata",
      "Mcal. Estigarribia",
    ]
  },
  {
    "name": "Alto Paraguay",
    "capital": "Fuerte Olimpo",
    "cidades": [
      "Bahía Negra",
      "Carmelo Peralta",
      "Puerto Casado",
      "Fuerte Olimpo"
    ]
  }
];
