// import '../../modules/municipios/domain/entities/municipio_entity.dart';

// final municipiosParaguay = [
//   MunicipioEntity(id: "1", departamento: "1", name: 'Asunción'),
//   MunicipioEntity(id: "2", departamento: "17", name: 'Bahía Negra'),
//   MunicipioEntity(id: "3", departamento: "17", name: 'Carmelo Peralta'),
//   MunicipioEntity(id: "4", departamento: "17", name: 'Puerto Casado'),
//   MunicipioEntity(id: "5", departamento: "17", name: 'Fuerte Olimpo'),
//   MunicipioEntity(id: "6", departamento: "11", name: 'Ciudad del Este'),
//   MunicipioEntity(
//       id: "7", departamento: "11", name: 'Doctor Juan León Mallorquín'),
//   MunicipioEntity(id: "8", departamento: "11", name: 'Doctor Raúl Peña'),
//   MunicipioEntity(
//       id: "9", departamento: "11", name: 'Domingo Martínez de Irala'),
//   MunicipioEntity(id: "10", departamento: "11", name: 'Hernandarias'),
//   MunicipioEntity(id: "11", departamento: "11", name: 'Iruña'),
//   MunicipioEntity(id: "12", departamento: "11", name: 'Itakyry'),
//   MunicipioEntity(id: "13", departamento: "11", name: 'Juan E. O\'Leary'),
//   MunicipioEntity(id: "14", departamento: "11", name: 'Los Cedrales'),
//   MunicipioEntity(id: "15", departamento: "11", name: 'Mbaracayú'),
//   MunicipioEntity(id: "16", departamento: "11", name: 'Minga Guazú'),
//   MunicipioEntity(id: "17", departamento: "11", name: 'Minga Porá'),
//   MunicipioEntity(id: "18", departamento: "11", name: 'Naranjal'),
//   MunicipioEntity(id: "19", departamento: "11", name: 'Ñacunday'),
//   MunicipioEntity(id: "20", departamento: "11", name: 'Presidente Franco'),
//   MunicipioEntity(id: "21", departamento: "11", name: 'San Alberto'),
//   MunicipioEntity(id: "22", departamento: "11", name: 'San Cristóbal'),
//   MunicipioEntity(id: "23", departamento: "11", name: 'Santa Fe del Paraná'),
//   MunicipioEntity(id: "24", departamento: "11", name: 'Santa Rita'),
//   MunicipioEntity(id: "25", departamento: "11", name: 'Santa Rosa del Monday'),
//   MunicipioEntity(id: "26", departamento: "11", name: 'Tavapy'),
//   MunicipioEntity(id: "27", departamento: "11", name: 'Colonia Yguazú'),
//   MunicipioEntity(id: "28", departamento: "13", name: 'Bella Vista Norte'),
//   MunicipioEntity(id: "29", departamento: "13", name: 'Capitán Bado'),
//   MunicipioEntity(id: "30", departamento: "13", name: 'Pedro Juan Caballero'),
//   MunicipioEntity(id: "31", departamento: "13", name: 'Zanja Pytá'),
//   MunicipioEntity(id: "32", departamento: "13", name: 'Karapaí'),
//   MunicipioEntity(id: "33", departamento: "16", name: 'Filadelfia'),
//   MunicipioEntity(id: "34", departamento: "16", name: 'Loma Plata'),
//   MunicipioEntity(id: "35", departamento: "16", name: 'Mcal. Estigarribia'),
//   MunicipioEntity(id: "36", departamento: "6", name: 'Caaguazú'),
//   MunicipioEntity(id: "37", departamento: "6", name: 'Carayaó'),
//   MunicipioEntity(id: "38", departamento: "6", name: 'Cnel. Oviedo'),
//   MunicipioEntity(id: "39", departamento: "6", name: 'Doctor Cecilio Báez'),
//   MunicipioEntity(id: "40", departamento: "6", name: 'J.E. Estigarribia'),
//   MunicipioEntity(id: "41", departamento: "6", name: 'Campo 9'),
//   MunicipioEntity(
//       id: "42", departamento: "6", name: 'Doctor Juan Manuel Frutos'),
//   MunicipioEntity(id: "43", departamento: "6", name: 'José Domingo Ocampos'),
//   MunicipioEntity(id: "44", departamento: "6", name: 'La Pastora'),
//   MunicipioEntity(
//       id: "45", departamento: "6", name: 'Mcal. Francisco S. López'),
//   MunicipioEntity(id: "46", departamento: "6", name: 'Nueva Londres'),
//   MunicipioEntity(id: "47", departamento: "6", name: 'Nueva Toledo'),
//   MunicipioEntity(id: "48", departamento: "6", name: 'Raúl Arsenio Oviedo'),
//   MunicipioEntity(id: "49", departamento: "6", name: 'Repatriación'),
//   MunicipioEntity(id: "50", departamento: "6", name: 'R. I. Tres Corrales'),
//   MunicipioEntity(id: "51", departamento: "6", name: 'San Joaquín'),
//   MunicipioEntity(id: "52", departamento: "6", name: 'San José de los Arroyos'),
//   MunicipioEntity(id: "53", departamento: "6", name: 'Mbutuy'),
//   MunicipioEntity(id: "54", departamento: "6", name: 'Simón Bolívar'),
//   MunicipioEntity(id: "55", departamento: "6", name: 'Tembiaporá'),
//   MunicipioEntity(id: "56", departamento: "6", name: 'Tres de Febrero'),
//   MunicipioEntity(id: "57", departamento: "6", name: 'Vaquería'),
//   MunicipioEntity(id: "58", departamento: "6", name: 'Yhú'),
//   MunicipioEntity(id: "59", departamento: "7", name: '3 de Mayo'),
//   MunicipioEntity(id: "60", departamento: "7", name: 'Abaí'),
//   MunicipioEntity(id: "61", departamento: "7", name: 'Buena Vista'),
//   MunicipioEntity(id: "62", departamento: "7", name: 'Caazapá'),
//   MunicipioEntity(
//       id: "63", departamento: "7", name: 'Doctor Moisés S. Bertoni'),
//   MunicipioEntity(id: "64", departamento: "7", name: 'Fulgencio Yegros'),
//   MunicipioEntity(
//       id: "65", departamento: "7", name: 'General Higinio Morínigo'),
//   MunicipioEntity(id: "66", departamento: "7", name: 'Maciel'),
//   MunicipioEntity(id: "67", departamento: "7", name: 'San Juan Nepomuceno'),
//   MunicipioEntity(id: "68", departamento: "7", name: 'Tavaí'),
//   MunicipioEntity(id: "69", departamento: "7", name: 'Yuty'),
//   MunicipioEntity(id: "70", departamento: "14", name: 'Colonia Anahí'),
//   MunicipioEntity(id: "71", departamento: "14", name: 'Corpus Christi'),
//   MunicipioEntity(id: "72", departamento: "14", name: 'Curuguaty'),
//   MunicipioEntity(
//       id: "73", departamento: "14", name: 'Gral. Francisco Caballero Álvarez'),
//   MunicipioEntity(id: "74", departamento: "14", name: 'Itanará'),
//   MunicipioEntity(id: "75", departamento: "14", name: 'Katueté'),
//   MunicipioEntity(id: "76", departamento: "14", name: 'La Paloma'),
//   MunicipioEntity(id: "77", departamento: "14", name: 'Maracaná'),
//   MunicipioEntity(id: "78", departamento: "14", name: 'Nueva Esperanza'),
//   MunicipioEntity(id: "79", departamento: "14", name: 'Salto del Guairá'),
//   MunicipioEntity(id: "80", departamento: "14", name: 'Villa Ygatimí'),
//   MunicipioEntity(id: "81", departamento: "14", name: 'Yasy Cañy'),
//   MunicipioEntity(id: "82", departamento: "14", name: 'Ybyrarovaná'),
//   MunicipioEntity(id: "83", departamento: "14", name: 'Ypejhú'),
//   MunicipioEntity(id: "84", departamento: "14", name: 'Yby Pytá'),
//   MunicipioEntity(id: "85", departamento: "1", name: 'Areguá'),
//   MunicipioEntity(id: "86", departamento: "1", name: 'Capiatá'),
//   MunicipioEntity(id: "87", departamento: "1", name: 'Fernando de la Mora'),
//   MunicipioEntity(id: "88", departamento: "1", name: 'Guarambaré'),
//   MunicipioEntity(id: "89", departamento: "1", name: 'Itá'),
//   MunicipioEntity(id: "90", departamento: "1", name: 'Itauguá'),
//   MunicipioEntity(id: "91", departamento: "1", name: 'J. Augusto Saldivar'),
//   MunicipioEntity(id: "92", departamento: "1", name: 'Lambaré'),
//   MunicipioEntity(id: "93", departamento: "1", name: 'Limpio'),
//   MunicipioEntity(id: "94", departamento: "1", name: 'Luque'),
//   MunicipioEntity(id: "95", departamento: "1", name: 'Mariano Roque Alonso'),
//   MunicipioEntity(id: "96", departamento: "1", name: 'Ñemby'),
//   MunicipioEntity(id: "97", departamento: "1", name: 'Nueva Italia'),
//   MunicipioEntity(id: "98", departamento: "1", name: 'San Antonio'),
//   MunicipioEntity(id: "99", departamento: "1", name: 'San Lorenzo'),
//   MunicipioEntity(id: "100", departamento: "1", name: 'Villa Elisa'),
//   MunicipioEntity(id: "101", departamento: "1", name: 'Villeta'),
//   MunicipioEntity(id: "102", departamento: "1", name: 'Ypacaraí'),
//   MunicipioEntity(id: "103", departamento: "1", name: 'Ypané'),
//   MunicipioEntity(id: "104", departamento: "2", name: 'Arroyito'),
//   MunicipioEntity(id: "105", departamento: "2", name: 'Azotey'),
//   MunicipioEntity(id: "106", departamento: "2", name: 'Belén'),
//   MunicipioEntity(id: "107", departamento: "2", name: 'Concepción'),
//   MunicipioEntity(id: "108", departamento: "2", name: 'Horqueta'),
//   MunicipioEntity(id: "109", departamento: "2", name: 'Loreto'),
//   MunicipioEntity(id: "110", departamento: "2", name: 'San Carlos del Apa'),
//   MunicipioEntity(id: "111", departamento: "2", name: 'San Lázaro'),
//   MunicipioEntity(id: "112", departamento: "2", name: 'Yby Yaú'),
//   MunicipioEntity(
//       id: "113", departamento: "2", name: 'Sargento José Félix López'),
//   MunicipioEntity(id: "114", departamento: "2", name: 'San Alfredo'),
//   MunicipioEntity(id: "115", departamento: "2", name: 'Paso Barreto'),
//   MunicipioEntity(id: "116", departamento: "4", name: 'Altos'),
//   MunicipioEntity(id: "117", departamento: "4", name: 'Arroyos y Esteros'),
//   MunicipioEntity(id: "118", departamento: "4", name: 'Atyrá'),
//   MunicipioEntity(id: "119", departamento: "4", name: 'Caacupé'),
//   MunicipioEntity(id: "120", departamento: "4", name: 'Caraguatay'),
//   MunicipioEntity(id: "121", departamento: "4", name: 'Emboscada'),
//   MunicipioEntity(id: "122", departamento: "4", name: 'Eusebio Ayala'),
//   MunicipioEntity(id: "123", departamento: "4", name: 'Isla Pucú'),
//   MunicipioEntity(id: "124", departamento: "4", name: 'Itacurubí'),
//   MunicipioEntity(id: "125", departamento: "4", name: 'Juan de Mena'),
//   MunicipioEntity(id: "126", departamento: "4", name: 'Loma Grande'),
//   MunicipioEntity(id: "127", departamento: "4", name: 'Mbocayaty del Yhaguy'),
//   MunicipioEntity(id: "128", departamento: "4", name: 'Nueva Colombia'),
//   MunicipioEntity(id: "129", departamento: "4", name: 'Piribebuy'),
//   MunicipioEntity(id: "130", departamento: "4", name: 'Primero de Marzo'),
//   MunicipioEntity(id: "131", departamento: "4", name: 'San Bernardino'),
//   MunicipioEntity(id: "132", departamento: "4", name: 'San José Obrero'),
//   MunicipioEntity(id: "133", departamento: "4", name: 'Santa Elena'),
//   MunicipioEntity(id: "134", departamento: "4", name: 'Tobatí'),
//   MunicipioEntity(id: "135", departamento: "4", name: 'Valenzuela'),
//   MunicipioEntity(id: "136", departamento: "5", name: 'Borja'),
//   MunicipioEntity(id: "137", departamento: "5", name: 'Colonia Independencia'),
//   MunicipioEntity(id: "138", departamento: "5", name: 'Coronel Martínez'),
//   MunicipioEntity(id: "139", departamento: "5", name: 'Dr. Bottrell'),
//   MunicipioEntity(id: "140", departamento: "5", name: 'Fassardi'),
//   MunicipioEntity(id: "141", departamento: "5", name: 'Félix Pérez Cardozo'),
//   MunicipioEntity(id: "142", departamento: "5", name: 'Garay'),
//   MunicipioEntity(id: "143", departamento: "5", name: 'Itapé'),
//   MunicipioEntity(id: "144", departamento: "5", name: 'Iturbe'),
//   MunicipioEntity(id: "145", departamento: "5", name: 'Mbocayaty'),
//   MunicipioEntity(id: "146", departamento: "5", name: 'Natalicio Talavera'),
//   MunicipioEntity(id: "147", departamento: "5", name: 'Ñumí'),
//   MunicipioEntity(id: "148", departamento: "5", name: 'Paso Yobái'),
//   MunicipioEntity(id: "149", departamento: "5", name: 'San Salvador'),
//   MunicipioEntity(id: "150", departamento: "5", name: 'Tebicuary'),
//   MunicipioEntity(id: "151", departamento: "5", name: 'Troche'),
//   MunicipioEntity(id: "152", departamento: "5", name: 'Villarrica'),
//   MunicipioEntity(id: "153", departamento: "5", name: 'Yataity'),
//   MunicipioEntity(id: "154", departamento: "8", name: 'Alto Verá'),
//   MunicipioEntity(id: "155", departamento: "8", name: 'Bella Vista'),
//   MunicipioEntity(id: "156", departamento: "8", name: 'Cambyretá'),
//   MunicipioEntity(id: "157", departamento: "8", name: 'Capitán Meza'),
//   MunicipioEntity(id: "158", departamento: "8", name: 'Capitán Miranda'),
//   MunicipioEntity(id: "159", departamento: "8", name: 'Carlos Antonio López'),
//   MunicipioEntity(id: "160", departamento: "8", name: 'Carmen del Paraná'),
//   MunicipioEntity(id: "161", departamento: "8", name: 'Coronel Bogado'),
//   MunicipioEntity(id: "162", departamento: "8", name: 'Edelira'),
//   MunicipioEntity(id: "163", departamento: "8", name: 'Encarnación'),
//   MunicipioEntity(id: "164", departamento: "8", name: 'Fram'),
//   MunicipioEntity(id: "165", departamento: "8", name: 'General Artigas'),
//   MunicipioEntity(id: "166", departamento: "8", name: 'General Delgado'),
//   MunicipioEntity(id: "167", departamento: "8", name: 'Hohenau'),
//   MunicipioEntity(id: "168", departamento: "8", name: 'Itapúa Poty'),
//   MunicipioEntity(id: "169", departamento: "8", name: 'Jesús'),
//   MunicipioEntity(id: "170", departamento: "8", name: 'Colonia La Paz'),
//   MunicipioEntity(id: "171", departamento: "8", name: 'José Leandro Oviedo'),
//   MunicipioEntity(id: "172", departamento: "8", name: 'Mayor Otaño'),
//   MunicipioEntity(id: "173", departamento: "8", name: 'Natalio'),
//   MunicipioEntity(id: "174", departamento: "8", name: 'Nueva Alborada'),
//   MunicipioEntity(id: "175", departamento: "8", name: 'Obligado'),
//   MunicipioEntity(id: "176", departamento: "8", name: 'Pirapó'),
//   MunicipioEntity(id: "177", departamento: "8", name: 'San Cosme y Damián'),
//   MunicipioEntity(id: "178", departamento: "8", name: 'San Juan del Paraná'),
//   MunicipioEntity(id: "179", departamento: "8", name: 'San Pedro del Paraná'),
//   MunicipioEntity(id: "180", departamento: "8", name: 'San Rafael del Paraná'),
//   MunicipioEntity(id: "181", departamento: "8", name: 'Maria Auxiliadora'),
//   MunicipioEntity(id: "182", departamento: "8", name: 'Trinidad'),
//   MunicipioEntity(id: "183", departamento: "8", name: 'Yatytay'),
//   MunicipioEntity(id: "184", departamento: "9", name: 'Ayolas'),
//   MunicipioEntity(id: "185", departamento: "9", name: 'San Ignacio'),
//   MunicipioEntity(id: "186", departamento: "9", name: 'San Juan Bautista'),
//   MunicipioEntity(id: "187", departamento: "9", name: 'San Miguel'),
//   MunicipioEntity(id: "188", departamento: "9", name: 'San Patricio'),
//   MunicipioEntity(id: "189", departamento: "9", name: 'Santa María'),
//   MunicipioEntity(id: "190", departamento: "9", name: 'Santa Rosa'),
//   MunicipioEntity(id: "191", departamento: "9", name: 'Santiago'),
//   MunicipioEntity(id: "192", departamento: "9", name: 'Villa Florida'),
//   MunicipioEntity(id: "193", departamento: "9", name: 'Yabebyry'),
//   MunicipioEntity(id: "194", departamento: "12", name: 'Alberdi'),
//   MunicipioEntity(id: "195", departamento: "12", name: 'Cerrito'),
//   MunicipioEntity(id: "196", departamento: "12", name: 'Desmochados'),
//   MunicipioEntity(
//       id: "197", departamento: "12", name: 'General José Eduvigis Díaz'),
//   MunicipioEntity(id: "198", departamento: "12", name: 'Guazú Cuá'),
//   MunicipioEntity(id: "199", departamento: "12", name: 'Humaitá'),
//   MunicipioEntity(id: "200", departamento: "12", name: 'Isla Umbú'),
//   MunicipioEntity(id: "201", departamento: "12", name: 'Laureles'),
//   MunicipioEntity(
//       id: "202", departamento: "12", name: 'Mayor José J. Martínez'),
//   MunicipioEntity(id: "203", departamento: "12", name: 'Paso de Patria'),
//   MunicipioEntity(id: "204", departamento: "12", name: 'Pilar'),
//   MunicipioEntity(
//       id: "205", departamento: "12", name: 'San Juan Bautista del Ñeembucú'),
//   MunicipioEntity(id: "206", departamento: "12", name: 'Tacuaras'),
//   MunicipioEntity(id: "207", departamento: "12", name: 'Villa Franca'),
//   MunicipioEntity(id: "208", departamento: "12", name: 'Villalbín'),
//   MunicipioEntity(id: "209", departamento: "12", name: 'Villa Oliva'),
//   MunicipioEntity(id: "210", departamento: "10", name: 'Acahay'),
//   MunicipioEntity(id: "211", departamento: "10", name: 'Caapucú'),
//   MunicipioEntity(id: "212", departamento: "10", name: 'Carapeguá'),
//   MunicipioEntity(id: "213", departamento: "10", name: 'Escobar'),
//   MunicipioEntity(
//       id: "214", departamento: "10", name: 'Gral. Bernardino Caballero'),
//   MunicipioEntity(id: "215", departamento: "10", name: 'La Colmena'),
//   MunicipioEntity(id: "216", departamento: "10", name: 'María Antonia'),
//   MunicipioEntity(id: "217", departamento: "10", name: 'Mbuyapey'),
//   MunicipioEntity(id: "218", departamento: "10", name: 'Paraguarí'),
//   MunicipioEntity(id: "219", departamento: "10", name: 'Pirayú'),
//   MunicipioEntity(id: "220", departamento: "10", name: 'Quiindy'),
//   MunicipioEntity(id: "221", departamento: "10", name: 'Quyquyhó'),
//   MunicipioEntity(
//       id: "222", departamento: "10", name: 'San Roque González de Santa Cruz'),
//   MunicipioEntity(id: "223", departamento: "10", name: 'Sapucai'),
//   MunicipioEntity(id: "224", departamento: "10", name: 'Tebicuarymí'),
//   MunicipioEntity(id: "225", departamento: "10", name: 'Yaguarón'),
//   MunicipioEntity(id: "226", departamento: "10", name: 'Ybycuí'),
//   MunicipioEntity(id: "227", departamento: "10", name: 'Ybytymí'),
//   MunicipioEntity(id: "228", departamento: "15", name: 'Benjamín Aceval'),
//   MunicipioEntity(id: "229", departamento: "15", name: 'Dr. José Falcón'),
//   MunicipioEntity(
//       id: "230", departamento: "15", name: 'General José María Bruguez'),
//   MunicipioEntity(id: "231", departamento: "15", name: 'Nanawa'),
//   MunicipioEntity(id: "232", departamento: "15", name: 'Colonia Paratodo'),
//   MunicipioEntity(id: "233", departamento: "15", name: 'Pozo Colorado'),
//   MunicipioEntity(id: "234", departamento: "15", name: 'Puerto Pinasco'),
//   MunicipioEntity(id: "235", departamento: "15", name: 'Tte. Irala Fernández'),
//   MunicipioEntity(id: "236", departamento: "15", name: 'Esteban Martínez'),
//   MunicipioEntity(id: "237", departamento: "15", name: 'Villa Hayes'),
//   MunicipioEntity(id: "238", departamento: "3", name: 'Antequera'),
//   MunicipioEntity(id: "239", departamento: "3", name: 'Capiibary'),
//   MunicipioEntity(id: "240", departamento: "3", name: 'Choré'),
//   MunicipioEntity(
//       id: "241", departamento: "3", name: 'General Elizardo Aquino'),
//   MunicipioEntity(
//       id: "242", departamento: "3", name: 'General Isidoro Resquín'),
//   MunicipioEntity(id: "243", departamento: "3", name: 'Guayaibí'),
//   MunicipioEntity(id: "244", departamento: "3", name: 'Itacurubí del Rosario'),
//   MunicipioEntity(id: "245", departamento: "3", name: 'Liberación'),
//   MunicipioEntity(id: "246", departamento: "3", name: 'Lima'),
//   MunicipioEntity(id: "247", departamento: "3", name: 'Rio Verde'),
//   MunicipioEntity(id: "248", departamento: "3", name: 'Nueva Germania'),
//   MunicipioEntity(id: "249", departamento: "3", name: 'San Estanislao'),
//   MunicipioEntity(id: "250", departamento: "3", name: 'San Pablo'),
//   MunicipioEntity(id: "251", departamento: "3", name: 'Villa de San Pedro'),
//   MunicipioEntity(id: "252", departamento: "3", name: 'San Vicente Pancholo'),
//   MunicipioEntity(id: "253", departamento: "3", name: 'Santa Rosa del Aguaray'),
//   MunicipioEntity(id: "254", departamento: "3", name: 'Tacuatí'),
//   MunicipioEntity(id: "255", departamento: "3", name: 'Unión'),
//   MunicipioEntity(id: "256", departamento: "3", name: '25 de Diciembre'),
//   MunicipioEntity(id: "257", departamento: "3", name: 'Villa del Rosario'),
//   MunicipioEntity(id: "258", departamento: "3", name: 'Yataity del Norte'),
//   MunicipioEntity(id: "259", departamento: "3", name: 'Yrybucuá'),
// ];
