import 'municipio_paraguay.dart';

final municipiosParaguay = [
  Municipio(id: 1, departamento: 1, name: 'Asunción'),
  Municipio(id: 2, departamento: 17, name: 'Bahía Negra'),
  Municipio(id: 3, departamento: 17, name: 'Carmelo Peralta'),
  Municipio(id: 4, departamento: 17, name: 'Puerto Casado'),
  Municipio(id: 5, departamento: 17, name: 'Fuerte Olimpo'),
  Municipio(id: 6, departamento: 11, name: 'Ciudad del Este'),
  Municipio(id: 7, departamento: 11, name: 'Doctor Juan León Mallorquín'),
  Municipio(id: 8, departamento: 11, name: 'Doctor Raúl Peña'),
  Municipio(id: 9, departamento: 11, name: 'Domingo Martínez de Irala'),
  Municipio(id: 10, departamento: 11, name: 'Hernandarias'),
  Municipio(id: 11, departamento: 11, name: 'Iruña'),
  Municipio(id: 12, departamento: 11, name: 'Itakyry'),
  Municipio(id: 13, departamento: 11, name: 'Juan E. O\'Leary'),
  Municipio(id: 14, departamento: 11, name: 'Los Cedrales'),
  Municipio(id: 15, departamento: 11, name: 'Mbaracayú'),
  Municipio(id: 16, departamento: 11, name: 'Minga Guazú'),
  Municipio(id: 17, departamento: 11, name: 'Minga Porá'),
  Municipio(id: 18, departamento: 11, name: 'Naranjal'),
  Municipio(id: 19, departamento: 11, name: 'Ñacunday'),
  Municipio(id: 20, departamento: 11, name: 'Presidente Franco'),
  Municipio(id: 21, departamento: 11, name: 'San Alberto'),
  Municipio(id: 22, departamento: 11, name: 'San Cristóbal'),
  Municipio(id: 23, departamento: 11, name: 'Santa Fe del Paraná'),
  Municipio(id: 24, departamento: 11, name: 'Santa Rita'),
  Municipio(id: 25, departamento: 11, name: 'Santa Rosa del Monday'),
  Municipio(id: 26, departamento: 11, name: 'Tavapy'),
  Municipio(id: 27, departamento: 11, name: 'Colonia Yguazú'),
  Municipio(id: 28, departamento: 13, name: 'Bella Vista Norte'),
  Municipio(id: 29, departamento: 13, name: 'Capitán Bado'),
  Municipio(id: 30, departamento: 13, name: 'Pedro Juan Caballero'),
  Municipio(id: 31, departamento: 13, name: 'Zanja Pytá'),
  Municipio(id: 32, departamento: 13, name: 'Karapaí'),
  Municipio(id: 33, departamento: 16, name: 'Filadelfia'),
  Municipio(id: 34, departamento: 16, name: 'Loma Plata'),
  Municipio(id: 35, departamento: 16, name: 'Mcal. Estigarribia'),
  Municipio(id: 36, departamento: 6, name: 'Caaguazú'),
  Municipio(id: 37, departamento: 6, name: 'Carayaó'),
  Municipio(id: 38, departamento: 6, name: 'Cnel. Oviedo'),
  Municipio(id: 39, departamento: 6, name: 'Doctor Cecilio Báez'),
  Municipio(id: 40, departamento: 6, name: 'J.E. Estigarribia'),
  Municipio(id: 41, departamento: 6, name: 'Campo 9'),
  Municipio(id: 42, departamento: 6, name: 'Doctor Juan Manuel Frutos'),
  Municipio(id: 43, departamento: 6, name: 'José Domingo Ocampos'),
  Municipio(id: 44, departamento: 6, name: 'La Pastora'),
  Municipio(id: 45, departamento: 6, name: 'Mcal. Francisco S. López'),
  Municipio(id: 46, departamento: 6, name: 'Nueva Londres'),
  Municipio(id: 47, departamento: 6, name: 'Nueva Toledo'),
  Municipio(id: 48, departamento: 6, name: 'Raúl Arsenio Oviedo'),
  Municipio(id: 49, departamento: 6, name: 'Repatriación'),
  Municipio(id: 50, departamento: 6, name: 'R. I. Tres Corrales'),
  Municipio(id: 51, departamento: 6, name: 'San Joaquín'),
  Municipio(id: 52, departamento: 6, name: 'San José de los Arroyos'),
  Municipio(id: 53, departamento: 6, name: 'Mbutuy'),
  Municipio(id: 54, departamento: 6, name: 'Simón Bolívar'),
  Municipio(id: 55, departamento: 6, name: 'Tembiaporá'),
  Municipio(id: 56, departamento: 6, name: 'Tres de Febrero'),
  Municipio(id: 57, departamento: 6, name: 'Vaquería'),
  Municipio(id: 58, departamento: 6, name: 'Yhú'),
  Municipio(id: 59, departamento: 7, name: '3 de Mayo'),
  Municipio(id: 60, departamento: 7, name: 'Abaí'),
  Municipio(id: 61, departamento: 7, name: 'Buena Vista'),
  Municipio(id: 62, departamento: 7, name: 'Caazapá'),
  Municipio(id: 63, departamento: 7, name: 'Doctor Moisés S. Bertoni'),
  Municipio(id: 64, departamento: 7, name: 'Fulgencio Yegros'),
  Municipio(id: 65, departamento: 7, name: 'General Higinio Morínigo'),
  Municipio(id: 66, departamento: 7, name: 'Maciel'),
  Municipio(id: 67, departamento: 7, name: 'San Juan Nepomuceno'),
  Municipio(id: 68, departamento: 7, name: 'Tavaí'),
  Municipio(id: 69, departamento: 7, name: 'Yuty'),
  Municipio(id: 70, departamento: 14, name: 'Colonia Anahí'),
  Municipio(id: 71, departamento: 14, name: 'Corpus Christi'),
  Municipio(id: 72, departamento: 14, name: 'Curuguaty'),
  Municipio(
      id: 73, departamento: 14, name: 'Gral. Francisco Caballero Álvarez'),
  Municipio(id: 74, departamento: 14, name: 'Itanará'),
  Municipio(id: 75, departamento: 14, name: 'Katueté'),
  Municipio(id: 76, departamento: 14, name: 'La Paloma'),
  Municipio(id: 77, departamento: 14, name: 'Maracaná'),
  Municipio(id: 78, departamento: 14, name: 'Nueva Esperanza'),
  Municipio(id: 79, departamento: 14, name: 'Salto del Guairá'),
  Municipio(id: 80, departamento: 14, name: 'Villa Ygatimí'),
  Municipio(id: 81, departamento: 14, name: 'Yasy Cañy'),
  Municipio(id: 82, departamento: 14, name: 'Ybyrarovaná'),
  Municipio(id: 83, departamento: 14, name: 'Ypejhú'),
  Municipio(id: 84, departamento: 14, name: 'Yby Pytá'),
  Municipio(id: 85, departamento: 1, name: 'Areguá'),
  Municipio(id: 86, departamento: 1, name: 'Capiatá'),
  Municipio(id: 87, departamento: 1, name: 'Fernando de la Mora'),
  Municipio(id: 88, departamento: 1, name: 'Guarambaré'),
  Municipio(id: 89, departamento: 1, name: 'Itá'),
  Municipio(id: 90, departamento: 1, name: 'Itauguá'),
  Municipio(id: 91, departamento: 1, name: 'J. Augusto Saldivar'),
  Municipio(id: 92, departamento: 1, name: 'Lambaré'),
  Municipio(id: 93, departamento: 1, name: 'Limpio'),
  Municipio(id: 94, departamento: 1, name: 'Luque'),
  Municipio(id: 95, departamento: 1, name: 'Mariano Roque Alonso'),
  Municipio(id: 96, departamento: 1, name: 'Ñemby'),
  Municipio(id: 97, departamento: 1, name: 'Nueva Italia'),
  Municipio(id: 98, departamento: 1, name: 'San Antonio'),
  Municipio(id: 99, departamento: 1, name: 'San Lorenzo'),
  Municipio(id: 100, departamento: 1, name: 'Villa Elisa'),
  Municipio(id: 101, departamento: 1, name: 'Villeta'),
  Municipio(id: 102, departamento: 1, name: 'Ypacaraí'),
  Municipio(id: 103, departamento: 1, name: 'Ypané'),
  Municipio(id: 104, departamento: 2, name: 'Arroyito'),
  Municipio(id: 105, departamento: 2, name: 'Azotey'),
  Municipio(id: 106, departamento: 2, name: 'Belén'),
  Municipio(id: 107, departamento: 2, name: 'Concepción'),
  Municipio(id: 108, departamento: 2, name: 'Horqueta'),
  Municipio(id: 109, departamento: 2, name: 'Loreto'),
  Municipio(id: 110, departamento: 2, name: 'San Carlos del Apa'),
  Municipio(id: 111, departamento: 2, name: 'San Lázaro'),
  Municipio(id: 112, departamento: 2, name: 'Yby Yaú'),
  Municipio(id: 113, departamento: 2, name: 'Sargento José Félix López'),
  Municipio(id: 114, departamento: 2, name: 'San Alfredo'),
  Municipio(id: 115, departamento: 2, name: 'Paso Barreto'),
  Municipio(id: 116, departamento: 4, name: 'Altos'),
  Municipio(id: 117, departamento: 4, name: 'Arroyos y Esteros'),
  Municipio(id: 118, departamento: 4, name: 'Atyrá'),
  Municipio(id: 119, departamento: 4, name: 'Caacupé'),
  Municipio(id: 120, departamento: 4, name: 'Caraguatay'),
  Municipio(id: 121, departamento: 4, name: 'Emboscada'),
  Municipio(id: 122, departamento: 4, name: 'Eusebio Ayala'),
  Municipio(id: 123, departamento: 4, name: 'Isla Pucú'),
  Municipio(id: 124, departamento: 4, name: 'Itacurubí'),
  Municipio(id: 125, departamento: 4, name: 'Juan de Mena'),
  Municipio(id: 126, departamento: 4, name: 'Loma Grande'),
  Municipio(id: 127, departamento: 4, name: 'Mbocayaty del Yhaguy'),
  Municipio(id: 128, departamento: 4, name: 'Nueva Colombia'),
  Municipio(id: 129, departamento: 4, name: 'Piribebuy'),
  Municipio(id: 130, departamento: 4, name: 'Primero de Marzo'),
  Municipio(id: 131, departamento: 4, name: 'San Bernardino'),
  Municipio(id: 132, departamento: 4, name: 'San José Obrero'),
  Municipio(id: 133, departamento: 4, name: 'Santa Elena'),
  Municipio(id: 134, departamento: 4, name: 'Tobatí'),
  Municipio(id: 135, departamento: 4, name: 'Valenzuela'),
  Municipio(id: 136, departamento: 5, name: 'Borja'),
  Municipio(id: 137, departamento: 5, name: 'Colonia Independencia'),
  Municipio(id: 138, departamento: 5, name: 'Coronel Martínez'),
  Municipio(id: 139, departamento: 5, name: 'Dr. Bottrell'),
  Municipio(id: 140, departamento: 5, name: 'Fassardi'),
  Municipio(id: 141, departamento: 5, name: 'Félix Pérez Cardozo'),
  Municipio(id: 142, departamento: 5, name: 'Garay'),
  Municipio(id: 143, departamento: 5, name: 'Itapé'),
  Municipio(id: 144, departamento: 5, name: 'Iturbe'),
  Municipio(id: 145, departamento: 5, name: 'Mbocayaty'),
  Municipio(id: 146, departamento: 5, name: 'Natalicio Talavera'),
  Municipio(id: 147, departamento: 5, name: 'Ñumí'),
  Municipio(id: 148, departamento: 5, name: 'Paso Yobái'),
  Municipio(id: 149, departamento: 5, name: 'San Salvador'),
  Municipio(id: 150, departamento: 5, name: 'Tebicuary'),
  Municipio(id: 151, departamento: 5, name: 'Troche'),
  Municipio(id: 152, departamento: 5, name: 'Villarrica'),
  Municipio(id: 153, departamento: 5, name: 'Yataity'),
  Municipio(id: 154, departamento: 8, name: 'Alto Verá'),
  Municipio(id: 155, departamento: 8, name: 'Bella Vista'),
  Municipio(id: 156, departamento: 8, name: 'Cambyretá'),
  Municipio(id: 157, departamento: 8, name: 'Capitán Meza'),
  Municipio(id: 158, departamento: 8, name: 'Capitán Miranda'),
  Municipio(id: 159, departamento: 8, name: 'Carlos Antonio López'),
  Municipio(id: 160, departamento: 8, name: 'Carmen del Paraná'),
  Municipio(id: 161, departamento: 8, name: 'Coronel Bogado'),
  Municipio(id: 162, departamento: 8, name: 'Edelira'),
  Municipio(id: 163, departamento: 8, name: 'Encarnación'),
  Municipio(id: 164, departamento: 8, name: 'Fram'),
  Municipio(id: 165, departamento: 8, name: 'General Artigas'),
  Municipio(id: 166, departamento: 8, name: 'General Delgado'),
  Municipio(id: 167, departamento: 8, name: 'Hohenau'),
  Municipio(id: 168, departamento: 8, name: 'Itapúa Poty'),
  Municipio(id: 169, departamento: 8, name: 'Jesús'),
  Municipio(id: 170, departamento: 8, name: 'Colonia La Paz'),
  Municipio(id: 171, departamento: 8, name: 'José Leandro Oviedo'),
  Municipio(id: 172, departamento: 8, name: 'Mayor Otaño'),
  Municipio(id: 173, departamento: 8, name: 'Natalio'),
  Municipio(id: 174, departamento: 8, name: 'Nueva Alborada'),
  Municipio(id: 175, departamento: 8, name: 'Obligado'),
  Municipio(id: 176, departamento: 8, name: 'Pirapó'),
  Municipio(id: 177, departamento: 8, name: 'San Cosme y Damián'),
  Municipio(id: 178, departamento: 8, name: 'San Juan del Paraná'),
  Municipio(id: 179, departamento: 8, name: 'San Pedro del Paraná'),
  Municipio(id: 180, departamento: 8, name: 'San Rafael del Paraná'),
  Municipio(id: 181, departamento: 8, name: 'Maria Auxiliadora'),
  Municipio(id: 182, departamento: 8, name: 'Trinidad'),
  Municipio(id: 183, departamento: 8, name: 'Yatytay'),
  Municipio(id: 184, departamento: 9, name: 'Ayolas'),
  Municipio(id: 185, departamento: 9, name: 'San Ignacio'),
  Municipio(id: 186, departamento: 9, name: 'San Juan Bautista'),
  Municipio(id: 187, departamento: 9, name: 'San Miguel'),
  Municipio(id: 188, departamento: 9, name: 'San Patricio'),
  Municipio(id: 189, departamento: 9, name: 'Santa María'),
  Municipio(id: 190, departamento: 9, name: 'Santa Rosa'),
  Municipio(id: 191, departamento: 9, name: 'Santiago'),
  Municipio(id: 192, departamento: 9, name: 'Villa Florida'),
  Municipio(id: 193, departamento: 9, name: 'Yabebyry'),
  Municipio(id: 194, departamento: 12, name: 'Alberdi'),
  Municipio(id: 195, departamento: 12, name: 'Cerrito'),
  Municipio(id: 196, departamento: 12, name: 'Desmochados'),
  Municipio(id: 197, departamento: 12, name: 'General José Eduvigis Díaz'),
  Municipio(id: 198, departamento: 12, name: 'Guazú Cuá'),
  Municipio(id: 199, departamento: 12, name: 'Humaitá'),
  Municipio(id: 200, departamento: 12, name: 'Isla Umbú'),
  Municipio(id: 201, departamento: 12, name: 'Laureles'),
  Municipio(id: 202, departamento: 12, name: 'Mayor José J. Martínez'),
  Municipio(id: 203, departamento: 12, name: 'Paso de Patria'),
  Municipio(id: 204, departamento: 12, name: 'Pilar'),
  Municipio(id: 205, departamento: 12, name: 'San Juan Bautista del Ñeembucú'),
  Municipio(id: 206, departamento: 12, name: 'Tacuaras'),
  Municipio(id: 207, departamento: 12, name: 'Villa Franca'),
  Municipio(id: 208, departamento: 12, name: 'Villalbín'),
  Municipio(id: 209, departamento: 12, name: 'Villa Oliva'),
  Municipio(id: 210, departamento: 10, name: 'Acahay'),
  Municipio(id: 211, departamento: 10, name: 'Caapucú'),
  Municipio(id: 212, departamento: 10, name: 'Carapeguá'),
  Municipio(id: 213, departamento: 10, name: 'Escobar'),
  Municipio(id: 214, departamento: 10, name: 'Gral. Bernardino Caballero'),
  Municipio(id: 215, departamento: 10, name: 'La Colmena'),
  Municipio(id: 216, departamento: 10, name: 'María Antonia'),
  Municipio(id: 217, departamento: 10, name: 'Mbuyapey'),
  Municipio(id: 218, departamento: 10, name: 'Paraguarí'),
  Municipio(id: 219, departamento: 10, name: 'Pirayú'),
  Municipio(id: 220, departamento: 10, name: 'Quiindy'),
  Municipio(id: 221, departamento: 10, name: 'Quyquyhó'),
  Municipio(
      id: 222, departamento: 10, name: 'San Roque González de Santa Cruz'),
  Municipio(id: 223, departamento: 10, name: 'Sapucai'),
  Municipio(id: 224, departamento: 10, name: 'Tebicuarymí'),
  Municipio(id: 225, departamento: 10, name: 'Yaguarón'),
  Municipio(id: 226, departamento: 10, name: 'Ybycuí'),
  Municipio(id: 227, departamento: 10, name: 'Ybytymí'),
  Municipio(id: 228, departamento: 15, name: 'Benjamín Aceval'),
  Municipio(id: 229, departamento: 15, name: 'Dr. José Falcón'),
  Municipio(id: 230, departamento: 15, name: 'General José María Bruguez'),
  Municipio(id: 231, departamento: 15, name: 'Nanawa'),
  Municipio(id: 232, departamento: 15, name: 'Colonia Paratodo'),
  Municipio(id: 233, departamento: 15, name: 'Pozo Colorado'),
  Municipio(id: 234, departamento: 15, name: 'Puerto Pinasco'),
  Municipio(id: 235, departamento: 15, name: 'Tte. Irala Fernández'),
  Municipio(id: 236, departamento: 15, name: 'Esteban Martínez'),
  Municipio(id: 237, departamento: 15, name: 'Villa Hayes'),
  Municipio(id: 238, departamento: 3, name: 'Antequera'),
  Municipio(id: 239, departamento: 3, name: 'Capiibary'),
  Municipio(id: 240, departamento: 3, name: 'Choré'),
  Municipio(id: 241, departamento: 3, name: 'General Elizardo Aquino'),
  Municipio(id: 242, departamento: 3, name: 'General Isidoro Resquín'),
  Municipio(id: 243, departamento: 3, name: 'Guayaibí'),
  Municipio(id: 244, departamento: 3, name: 'Itacurubí del Rosario'),
  Municipio(id: 245, departamento: 3, name: 'Liberación'),
  Municipio(id: 246, departamento: 3, name: 'Lima'),
  Municipio(id: 247, departamento: 3, name: 'Rio Verde'),
  Municipio(id: 248, departamento: 3, name: 'Nueva Germania'),
  Municipio(id: 249, departamento: 3, name: 'San Estanislao'),
  Municipio(id: 250, departamento: 3, name: 'San Pablo'),
  Municipio(id: 251, departamento: 3, name: 'Villa de San Pedro'),
  Municipio(id: 252, departamento: 3, name: 'San Vicente Pancholo'),
  Municipio(id: 253, departamento: 3, name: 'Santa Rosa del Aguaray'),
  Municipio(id: 254, departamento: 3, name: 'Tacuatí'),
  Municipio(id: 255, departamento: 3, name: 'Unión'),
  Municipio(id: 256, departamento: 3, name: '25 de Diciembre'),
  Municipio(id: 257, departamento: 3, name: 'Villa del Rosario'),
  Municipio(id: 258, departamento: 3, name: 'Yataity del Norte'),
  Municipio(id: 259, departamento: 3, name: 'Yrybucuá'),
];
